## Lecture 07: Pandas

In [1]:
#!pip install pandas 
# project yêu cầu pandas version 12.3.2?

In [2]:
import numpy as np
import pandas as pd

In [3]:
s1 = pd.Series(range(10,14), index=list("abcd"))
s1

a    10
b    11
c    12
d    13
dtype: int64

In [4]:
s1.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [5]:
s1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [6]:
s1.values

array([10, 11, 12, 13])

In [7]:
s1['a']

np.int64(10)

In [8]:
s1[0]

C:\Users\Admin\AppData\Local\Temp\ipykernel_22372\643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.int64(10)

In [9]:
s1.iloc[0]

np.int64(10)

In [10]:
s1.loc['a']

np.int64(10)

In [11]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                    'Florida': 170312, 'New York': 141297,
                    'Pennsylvania': 119280})
pop = pd.Series({'California': 39538223, 'Texas': 29145505,
                    'Florida': 21538187, 'New York': 20201249,
                    'Pennsylvania': 13002700})
data = pd.DataFrame({'area':area, 'pop':pop})

In [12]:
data

                area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [13]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [14]:
data[['pop','area']]

                   pop    area
California    39538223  423967
Texas         29145505  695662
Florida       21538187  170312
New York      20201249  141297
Pennsylvania  13002700  119280

In [15]:
data.iloc[0]

area      423967
pop     39538223
Name: California, dtype: int64

In [16]:
data.loc['Texas']

area      695662
pop     29145505
Name: Texas, dtype: int64

In [17]:
data.iloc[:2,:]

              area       pop
California  423967  39538223
Texas       695662  29145505

In [18]:
data

                area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [19]:
data.loc[:'Florida',:]

              area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [20]:
rng = np.random.default_rng(42)
ser = pd.Series(rng.integers(0, 10, 4))
df = pd.DataFrame(rng.integers(0, 10, (3, 4)),columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  4  8  0  6
1  2  0  5  9
2  7  7  7  7

In [21]:
ser

0    0
1    7
2    6
3    4
dtype: int64

In [22]:
np.exp(ser)

0       1.000000
1    1096.633158
2     403.428793
3      54.598150
dtype: float64

In [23]:
np.sin(df * np.pi / 4)

              A             B         C         D
0  1.224647e-16 -2.449294e-16  0.000000 -1.000000
1  1.000000e+00  0.000000e+00 -0.707107  0.707107
2 -7.071068e-01 -7.071068e-01 -0.707107 -0.707107

In [24]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 39538223, 'Texas': 29145505, 'Florida': 21538187}, name='population')
print(population)
print(area)

California    39538223
Texas         29145505
Florida       21538187
Name: population, dtype: int64
Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [25]:
 population/area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64

In [28]:
df_retail = pd.read_csv(r'data\OnlineRetail.csv')
df_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom

In [29]:
df_retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.4+ MB

In [30]:
df_retail.describe()

            Quantity      UnitPrice     CustomerID
count  203422.000000  203422.000000  150039.000000
mean        9.585684       4.877820   15240.234832
std       240.921315     113.686676    1717.658493
min    -74215.000000       0.000000   12346.000000
25%         1.000000       1.250000   13791.000000
50%         3.000000       2.100000   15061.000000
75%        10.000000       4.130000   16771.000000
max     74215.000000   38970.000000   18287.000000

In [32]:
df_retail[df_retail['Quantity']<0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
17,539994,22830,NaN,-1,2011-01-04 10:09:00,0.00,NaN,United Kingdom
18,539995,85064,NaN,-12,2011-01-04 10:12:00,0.00,NaN,United Kingdom
19,539996,21784,NaN,-10,2011-01-04 10:12:00,0.00,NaN,United Kingdom
22,539999,20892,NaN,-1,2011-01-04 10:16:00,0.00,NaN,United Kingdom
23,540000,84499,NaN,-9,2011-01-04 10:17:00,0.00,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
201945,C558531,22424,ENAMEL BREAD BIN CREAM,-1,2011-06-30 11:31:00,12.75,15039.0,United Kingdom
202318,C558553,23170,REGENCY TEA PLATE ROSES,-576,2011-06-30 12:44:00,1.45,17949.0,United Kingdom
202427,C558559,20749,ASSORTED COLOUR MINI CASES,-1,2011-06-30 13:20:00,7.95,17648.0,United Kingdom
202627,C558575,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,-24,2011-06-30 14:58:00,1.25,12674.0,France
203075,C558615,21845,DAIRY MAID STRIPE MUG,-4,2011-06-30 16:20:00,0.79,17719.0,United Kingdom

In [33]:
df_retail = df_retail[df_retail['Quantity']>0]
df_retail.describe()

            Quantity      UnitPrice     CustomerID
count  198968.000000  198968.000000  146488.000000
mean       10.932909       3.969454   15247.558571
std       172.155246      25.254535    1716.950147
min         1.000000       0.000000   12346.000000
25%         1.000000       1.250000   13802.000000
50%         4.000000       2.100000   15065.000000
75%        10.000000       4.130000   16779.000000
max     74215.000000    8142.750000   18287.000000

In [34]:
df_retail.info()

<class 'pandas.core.frame.DataFrame'>
Index: 198968 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    198968 non-null  object
 1   StockCode    198968 non-null  object
 2   Description  198697 non-null  object
 3   Quantity     198968 non-null  int64
 4   InvoiceDate  198968 non-null  object
 5   UnitPrice    198968 non-null  float64
 6   CustomerID   146488 non-null  float64
 7   Country      198968 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 13.7+ MB

In [35]:
#mask
df_retail.isnull()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
203417,False,False,False,False,False,False,False,False
203418,False,False,False,False,False,False,False,False
203419,False,False,False,False,False,False,False,False
203420,False,False,False,False,False,False,False,False
203421,False,False,False,False,False,False,False,False

In [36]:
df_retail.isnull().sum()

InvoiceNo          0
StockCode          0
Description      271
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     52480
Country            0
dtype: int64

In [40]:
df_clean = df_retail.dropna()

In [41]:
df_clean.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [43]:
df_clean.duplicated().sum()

np.int64(1482)

In [44]:
df_clean.drop_duplicates(inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_22372\2294670995.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.drop_duplicates(inplace=True)

In [45]:
df_clean.duplicated().sum()

np.int64(0)

In [46]:
#!pip install matplotlib seaborn
import matplotlib.pyplot as plt 
import seaborn as sns

In [47]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [48]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [49]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [57]:

df_male = titanic[titanic['sex'] == 'male']
df_male

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [58]:
df_male.isnull().sum()

survived         0
pclass           0
sex              0
age            124
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           471
embark_town      0
alive            0
alone            0
dtype: int64

In [59]:
mean_male = df_male['age'].mean()
df_male['age'] = df_male['age'].fillna(value=mean_male)
df_male.isna().sum()

C:\Users\Admin\AppData\Local\Temp\ipykernel_22372\209774407.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_male['age'] = df_male['age'].fillna(value=mean_male)

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           471
embark_town      0
alive            0
alone            0
dtype: int64

In [61]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 145006 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    145006 non-null  object
 1   StockCode    145006 non-null  object
 2   Description  145006 non-null  object
 3   Quantity     145006 non-null  int64
 4   InvoiceDate  145006 non-null  object
 5   UnitPrice    145006 non-null  float64
 6   CustomerID   145006 non-null  float64
 7   Country      145006 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 10.0+ MB

In [65]:
#correct data type
df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])
df_clean['CustomerID'] = df_clean['CustomerID'].astype(int).astype(str)

C:\Users\Admin\AppData\Local\Temp\ipykernel_22372\2900447974.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])
C:\Users\Admin\AppData\Local\Temp\ipykernel_22372\2900447974.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['CustomerID'] = df_clean['CustomerID'].astype(int).astype(str)

In [66]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 145006 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    145006 non-null  object
 1   StockCode    145006 non-null  object
 2   Description  145006 non-null  object
 3   Quantity     145006 non-null  int64
 4   InvoiceDate  145006 non-null  datetime64[ns]
 5   UnitPrice    145006 non-null  float64
 6   CustomerID   145006 non-null  object
 7   Country      145006 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 10.0+ MB

In [68]:
import yfinance as yf

#!pip install yfinance -q


tickers = ['AAPL', 'MSFT', 'AMZN']
start = "2024-01-01"
end = pd.Timestamp("today").normalize()

stock_data = yf.download(tickers, start=start, end=end, group_by='ticker')
stock_data.head()

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
C:\Users\Admin\AppData\Local\Temp\ipykernel_22372\2493555427.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stock_data = yf.download(tickers, start=start, end=end, group_by='ticker')
[*********************100%***********************]  3 of 3 completed

Ticker            AMZN                                                \
Price             Open        High         Low       Close    Volume
Date
2024-01-02  151.539993  152.380005  148.389999  149.929993  47339400
2024-01-03  149.199997  151.050003  148.330002  148.470001  49425500
2024-01-04  145.589996  147.380005  144.050003  144.570007  56039800
2024-01-05  144.690002  146.589996  144.529999  145.240005  45153100
2024-01-08  146.740005  149.399994  146.149994  149.100006  46757100

Ticker            MSFT                                                \
Price             Open        High         Low       Close    Volume
Date
2024-01-02  366.734456  368.735583  359.779590  363.801453  25258600
2024-01-03  361.976959  366.145958  361.486489  363.536652  23083500
2024-01-04  363.605317  365.988995  360.172024  360.927338  20901500
2024-01-05  361.937746  364.968850  359.514821  360.740997  21004600
2024-01-08  362.261421  368.048995  361.976970  367.548706  23134000

Ticker            AAPL
Price             Open        High         Low       Close    Volume
Date
2024-01-02  185.055273  186.330843  181.831767  183.562180  82488700
2024-01-03  182.158066  183.799489  181.376900  182.187729  58414500
2024-01-04  180.111236  181.040717  178.855462  179.873932  71983600
2024-01-05  179.953046  180.714417  178.153410  179.152100  62379700
2024-01-08  180.051916  183.522639  179.468523  183.483078  59144500

In [69]:
stock_data.tail()

Ticker            AMZN                                                \
Price             Open        High         Low       Close    Volume
Date
2026-07-02  241.610001  246.720001  241.080002  242.669998  48246400
2026-07-06  243.800003  246.039993  240.880005  244.160004  40044000
2026-07-07  246.979996  248.929993  242.699997  245.979996  40579600
2026-07-08  244.270004  244.800003  240.520004  243.619995  29653000
2026-07-09  239.820007  247.500000  238.250000  247.039993  38030100

Ticker            MSFT                                                \
Price             Open        High         Low       Close    Volume
Date
2026-07-02  384.480011  392.200012  383.700012  390.489990  42128900
2026-07-06  387.040009  389.149994  381.220001  386.739990  34224500
2026-07-07  392.489990  395.570007  388.220001  388.839996  29297500
2026-07-08  384.029999  385.309998  381.329987  383.339996  25908300
2026-07-09  374.450012  384.649994  373.350006  384.359985  31033500

Ticker            AAPL
Price             Open        High         Low       Close    Volume
Date
2026-07-02  294.119995  309.420013  293.679993  308.630005  75352800
2026-07-06  307.359985  314.200012  307.000000  312.660004  53590000
2026-07-07  315.290009  315.480011  310.149994  310.660004  42490000
2026-07-08  311.910004  314.820007  307.049988  313.390015  41323500
2026-07-09  310.510010  316.529999  308.160004  316.220001  48084300

## Bài tập: Lấy dữ liệu và xử lý missing trên bộ dữ liệu `tips`

1. Load bộ dữ liệu `tips` từ seaborn và in ra 5 dòng đầu.
2. Hiển thị thông tin tổng quan của `tips` bằng `info()` và `describe()`.
3. Chọn ra:
    - tất cả các dòng mà `sex` là `male`,
    - tất cả các dòng có `total_bill` lớn hơn 20,
    - cột `day` và `time` của 10 dòng đầu.
4. Lấy giá trị `tip` của dòng có chỉ số `0`, `5` và `10` bằng `.loc` và `.iloc`.
5. Tạo dataframe mới chỉ chứa các cột `total_bill`, `tip`, `sex`, `smoker`, `day`, `time`.

## Bài tập: Xử lý missing và chuyển kiểu dữ liệu

1. Kiểm tra số lượng giá trị thiếu mỗi cột trong `tips`.
2. Thay giá trị thiếu ở cột `tip` bằng trung bình của cột đó.
3. Xác nhận lại số giá trị thiếu sau khi xử lý.
4. Chuyển kiểu dữ liệu:
    - `sex` và `smoker` sang `category`,
    - `day` và `time` sang `category`,
    - `total_bill` và `tip` sang `float32`.
5. In ra kiểu dữ liệu (`dtypes`) của dataframe sau khi chuyển đổi.

## Pandas 2

In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],columns=['letter', 'number'])
df2 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],columns=['letter', 'number', 'animal'])

In [3]:
df1

  letter  number
0      a       1
1      b       2

In [4]:
df2

  letter  number animal
0      c       3    cat
1      d       4    dog

In [5]:
pd.concat([df1,df2], axis = 1)

  letter  number letter  number animal
0      a       1      c       3    cat
1      b       2      d       4    dog

In [8]:
print(df1,'\n', df2)

  letter  number
0      a       1
1      b       2
   letter  number animal
0      c       3    cat
1      d       4    dog

In [9]:
pd.concat([df1,df2], axis = 0, join='outer')

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [10]:
pd.concat([df1,df2], axis = 0, join='outer',ignore_index=True)

  letter  number animal
0      a       1    NaN
1      b       2    NaN
2      c       3    cat
3      d       4    dog

Practice: US States Data

Trong mục này, minh họa cách kết hợp và thao tác dữ liệu bằng cách sử dụng dữ liệu về các bang của Mỹ. Quá trình được thực hiện qua các bước sau:

1. **Chuẩn bị Dữ Liệu**:
   - Tải dữ liệu từ GitHub bao gồm các tệp: `state-population.csv`, `state-areas.csv`, và `state-abbrevs.csv`.
   - Đọc dữ liệu vào các DataFrame bằng `pd.read_csv`.

2. **Hiển thị Dữ Liệu**:
   - Hiển thị dữ liệu đầu của các tệp để kiểm tra cấu trúc và nội dung.

3. **Kết hợp Dữ Liệu**:
   - Kết hợp các DataFrame dựa trên các cột khóa. Ví dụ, kết hợp `pop` và `abbrevs` để có được tên đầy đủ của các bang trong DataFrame `population`.
   - Sử dụng `pd.merge` với tham số `how='outer'` để không bỏ qua dữ liệu nào dù có sự không khớp về nhãn.

4. **Xử lý Dữ Liệu Thiếu**:
   - Kiểm tra và xử lý các giá trị thiếu (`NaN`). Ví dụ, thêm tên đầy đủ cho các bang không có trong `abbrevs`.
   - Loại bỏ các hàng có giá trị thiếu không cần thiết cho phân tích tiếp theo.

5. **Tính Toán Mật Độ Dân Số**:
   - Chọn dữ liệu năm 2010 và tổng dân số để tính mật độ dân số.
   - Tạo cột mới `density` bằng cách chia dân số cho diện tích.
   - Sắp xếp kết quả để tìm các bang có mật độ dân số cao nhất và thấp nhất.

6. **Hiển thị Kết Quả**:
   - Hiển thị kết quả cuối cùng với mật độ dân số được sắp xếp, cho thấy Washington, DC có mật độ dân số cao nhất và Alaska thấp nhất.

In [11]:
url1 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv'
url2 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv'
url3 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv'

pop = pd.read_csv(url1)
areas = pd.read_csv(url2)
abbrevs = pd.read_csv(url3)

In [12]:
pop.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [13]:
areas.head()

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [15]:
abbrevs.head()

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [16]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [18]:
#1
planets['number'].sum()

np.int64(1848)

In [20]:
#2
planets['distance'].mean()

np.float64(264.06928217821786)

In [25]:
# 3
len(planets['method'].unique())

10

In [31]:
#4
planets['mass'].dropna().sort_values()

46      0.00360
128     0.00600
263     0.00755
133     0.00800
134     0.00800
         ...
3      19.40000
913    19.80000
63     20.60000
85     21.42000
321    25.00000
Name: mass, Length: 513, dtype: float64

In [32]:
df = pd.DataFrame({'key': list("ABCABC"),
                   "data":range(6)},
                   columns=['key','data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [34]:
list(df.groupby('key'))

[('A',
    key  data
  0   A     0
  3   A     3),
 ('B',
    key  data
  1   B     1
  4   B     4),
 ('C',
    key  data
  2   C     2
  5   C     5)]

In [36]:
for d in df.groupby('key'):
    print(d[1])

  key  data
0   A     0
3   A     3
  key  data
1   B     1
4   B     4
  key  data
2   C     2
5   C     5

In [ ]:
df.groupby('key').sum()

     data
key
A       3
B       5
C       7

In [39]:
df.groupby('key').sum().shape

(3, 1)

In [40]:
df1 = pd.DataFrame({'key': list("ABCABC"),
                    "data1":range(6),
                    'data2':range(6,12)},
                    columns=['key','data1','data2'])
df1

  key  data1  data2
0   A      0      6
1   B      1      7
2   C      2      8
3   A      3      9
4   B      4     10
5   C      5     11

In [41]:
df1.groupby('key').sum()

     data1  data2
key
A        3     15
B        5     17
C        7     19

In [42]:
df1.groupby('key').aggregate(['sum','min'])

    data1     data2
      sum min   sum min
key
A       3   0    15   6
B       5   1    17   7
C       7   2    19   8

In [43]:
def myfunc(x):
    return x.mean()//2

In [44]:
df1.groupby('key').aggregate(['sum','min',myfunc])

    data1            data2
      sum min myfunc   sum min myfunc
key
A       3   0    0.0    15   6    3.0
B       5   1    1.0    17   7    4.0
C       7   2    1.0    19   8    4.0

In [46]:
df1.groupby('key').agg({'data1':['sum'], "data2":myfunc})

    data1  data2
      sum myfunc
key
A       3    3.0
B       5    4.0
C       7    4.0

In [47]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [53]:
titanic.groupby(['sex','class'])['survived'].mean().unstack()

C:\Users\Admin\AppData\Local\Temp\ipykernel_12380\2728885616.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(['sex','class'])['survived'].mean().unstack()

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
# pd.pivot # pd.pivot_table?
pd.pivot_table(data= titanic,
               columns='class',
               index='sex',
               values='survived',
               margins= True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12380\2985034064.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(data= titanic,

class      First    Second     Third       All
sex
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

In [59]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [62]:
# pd.pivot # pd.pivot_table?
pd.pivot_table(data= titanic,
               columns='embark_town',
               index=['sex','pclass'],
               values='fare',
               aggfunc='mean')

embark_town     Cherbourg  Queenstown  Southampton
sex    pclass
female 1       115.640309   90.000000    99.026910
       2        25.268457   12.350000    21.912687
       3        14.694926   10.307833    18.670077
male   1        93.536707   90.000000    52.949947
       2        25.421250   12.350000    19.232474
       3         9.352237   11.924251    13.307149